#!/usr/bin/env python
# vim: set fileencoding=utf-8 :

print('importing')
import os
from diskrec.server import DiskrecServer

print('opening')
server = DiskrecServer()
print('listening')
server.listen()



